declare var define: any;

define([], () => {
    return {
        HeaderNormalText: "Normal text",
        HeaderH2: "Heading 1",
        HeaderH3: "Heading 2",
        HeaderH4: "Heading 3",
        HeaderBlockQuote: "Pull quote",
        AlignLeft: "Align left",
        AlignCenter: "Center",
        AlignRight: "Align right",
        AlignJustify: "Justify",
        ListBullet: "Bulleted list",
        ListNumbered: "Numbered list",
        StyleTitle: "Style",
        BoldTitle: "Bold (Ctrl+B)",
        ItalicTitle: "Italic (Ctrl+I)",
        UnderlineTitle: "Underline (Ctrl+U)",
        AlignTitle: "Align",
        ListTitle: "List",
        LinkTitle: "Hyperlink",
        MoreTitle: "More",
        FormattingPaneTitle: "Text formatting",
        CloseButton: "Close",
        InsertLinkTitle: "Insert link",
        AddressFieldLabel: "Address",
        TextToDisplayLabel: "Text to display",
        SaveButtonLabel: "Save",
        CancelButtonLabel: "Cancel",
        RemoveLinkLabel: "Remove link",
        ParagraphSectionTitle: "Paragraph",
        HyperlinkSectionTitle: "Hyperlink",
        UndoTitle: "Undo (Ctrl+Z)",
        RedoTitle: "Redo (Ctrl+Y)",
        ClearFormattingTitle: "Clear all formatting",
        FontStyleTitle: "Font style",
        FontSizeTitle: "Font size",
        StrikethroughTitle: "Strikethrough",
        SuperscriptTitle: "Superscript",
        SubscriptTitle: "Subscript",
        FontColorLabel: "Font Color",
        AutomaticFontColor: "Automatic",
        HighlightColorLabel: "Highlight color",
        NoColorHighlightColor: "No color",
        IncreaseIndentTitle: "Increase indent",
        DecreaseIndentTitle: "Decrease indent",
        ThemeColorsGroupName: "Theme colors",
        HighlightColorsGroupName: "Highlight colors",
        StandardColorsGroupName: "Standard colors",
        CustomColorsGroupName: "Custom Colors",
        ThemeColorDarker: "Theme darker",
        ThemeColorDark: "Theme dark",
        ThemeColorDarkAlt: "Theme dark alternate",
        ThemeColorPrimary: "Theme primary",
        ThemeColorSecondary: "Theme secondary",
        ThemeColorTertiary: "Neutral tertiary",
        ThemeColorNeutralSecondary: "Neutral secondary",
        ThemeColorNeutralPrimaryAlt: "Neutral primary alternate",
        ThemeColorNeutralPrimary: "Neutral primary",
        ThemeColorNeutralDark: "Neutral dark",
        HighlightColorYellow: "Yellow",
        HighlightColorGreen: "Green",
        HighlightColorAqua: "Aqua",
        HighlightColorMagenta: "Magenta",
        HighlightColorBlue: "Blue",
        HighlightColorRed: "Red",
        HighlightColorDarkblue: "Dark blue",
        HighlightColorTeal: "Teal",
        HighlightColorDarkgreen: "Dark green",
        HighlightColorPurple: "Purple",
        HighlightColorMaroon: "Maroon",
        HighlightColorGold: "Gold",
        HighlightColorDarkgrey: "Dark grey",
        HighlightColorGrey: "Grey",
        HighlightColorBlack: "Black",
        StandardColorDarkred: "Dark red",
        StandardColorRed: "Red",
        StandardColorOrange: "Orange",
        StandardColorYellow: "Yellow",
        StandardColorLightgreen: "Light green",
        StandardColorGreen: "Green",
        StandardColorLightblue: "Light blue",
        StandardColorBlue: "Blue",
        StandardColorDarkblue: "Dark blue",
        StandardColorPurple: "Purple"
    };
});